#!/usr/bin/env python3
"""R3 deterministic code generator for the unified ProjectConfig.

The generator has one public core:

    generate_project(device, project_config, pinmux, family, active_module=None)

Preview and ZIP export call this same function.  It never invents configuration
for a module that is absent from ProjectConfig.
"""

from __future__ import annotations

import json
import re

MAX_SYSCLK_HZ = 60_000_000
INTOSC1_HZ = 10_000_000

HDR = """// ============================================================================
// AUTO-GENERATED by C2000 Config Studio for F28034 [R3]
// Deterministic output: preview and ZIP export use the same generator core.
// SAFETY: ePWM outputs remain clamped until the application explicitly calls
// the generated EPWMx_ReleaseClamp() function.
// ============================================================================
"""

ADC_TRIGSEL = {
    "software": 0, "cpu_timer0": 1, "cpu_timer1": 2, "cpu_timer2": 3,
    "xint2": 4, "epwm1_soca": 5, "epwm1_socb": 6,
    "epwm2_soca": 7, "epwm2_socb": 8, "epwm3_soca": 9,
    "epwm3_socb": 10, "epwm4_soca": 11, "epwm4_socb": 12,
    "epwm5_soca": 13, "epwm5_socb": 14, "epwm6_soca": 15,
    "epwm6_socb": 16, "epwm7_soca": 17, "epwm7_socb": 18,
}
ADC_CHSEL = {f"ADCINA{i}": i for i in range(8)}
ADC_CHSEL.update({f"ADCINB{i}": 8 + i for i in range(8)})

PIN_PROFILES = {
    "gpio_output": {"pullup": "disable", "direction": "output"},
    "gpio_input": {"pullup": "enable", "direction": "input", "qualification": "sync"},
    "epwm_output": {"pullup": "disable"},
    "trip_async_input": {"pullup": "enable", "qualification": "async"},
    "i2c_sda": {"pullup": "enable", "qualification": "async",
                "note": "I2C is open-drain; external pull-up resistors are required."},
    "i2c_scla": {"pullup": "enable", "qualification": "async",
                 "note": "I2C is open-drain; external pull-up resistors are required."},
    "sci_rx": {"pullup": "enable", "qualification": "async"},
    "sci_tx": {"pullup": "enable"},
    "spi_input": {"pullup": "enable", "qualification": "async"},
    "spi_output": {"pullup": "enable"},
    "eqep_input": {"pullup": "enable", "qualification": "sync"},
    "adc_analog": {},
}


def _pin_def(pinmux: dict, pnum: int | str) -> dict | None:
    return pinmux.get("pins", {}).get(str(pnum))


def _pins(config: dict) -> list[dict]:
    raw = config.get("pins", {}) or {}
    if isinstance(raw, list):  # R2 import compatibility only
        return [dict(p) for p in raw]
    out = []
    for key, value in raw.items():
        p = dict(value or {})
        p.setdefault("physical_pin", int(key))
        p.setdefault("pin", p["physical_pin"])
        out.append(p)
    return sorted(out, key=lambda p: int(p.get("physical_pin", p.get("pin", 0))))


def _pnum(p: dict) -> int:
    return int(p.get("physical_pin", p.get("pin")))


def _function(p: dict) -> str:
    return str(p.get("function") or "").upper()


def _profile_for(pin: dict, option: dict | None) -> tuple[str, dict]:
    explicit = pin.get("electrical_profile") or (option or {}).get("generator_profile")
    if explicit:
        return explicit, PIN_PROFILES.get(explicit, {})
    fn = _function(pin)
    ptype = (option or {}).get("type", pin.get("type", ""))
    if int(pin.get("mux", 0)) == 0:
        name = "gpio_input" if pin.get("direction") == "input" else "gpio_output"
    elif fn.startswith("EPWM"):
        name = "epwm_output"
    elif fn.startswith("TZ"):
        name = "trip_async_input"
    elif ptype == "i2c":
        name = "i2c_sda" if "SDA" in fn else "i2c_scla"
    elif ptype == "sci":
        name = "sci_rx" if "RX" in fn else "sci_tx"
    elif ptype == "spi":
        name = "spi_input" if any(x in fn for x in ("SOMI", "SIMO")) else "spi_output"
    elif ptype == "eqep":
        name = "eqep_input"
    else:
        name = "gpio_input"
    return name, PIN_PROFILES[name]


def _mux_option(pdef: dict, pin: dict) -> dict | None:
    mux = int(pin.get("mux", 0))
    fn = _function(pin)
    return next((m for m in pdef.get("mux_options", [])
                 if int(m.get("mux", -1)) == mux
                 and str(m.get("function", "")).upper() == fn), None)


def gen_pinmux(config: dict, pinmux: dict) -> dict[str, str]:
    lines = [HDR, '#include "DSP2803x_Device.h"', '#include "pinmux_init.h"', "",
             "void Generated_PinMux_Init(void)", "{", "    EALLOW;"]
    emitted = 0
    for pin in _pins(config):
        pnum = _pnum(pin)
        pdef = _pin_def(pinmux, pnum)
        if not pdef or not pdef.get("configurable"):
            continue
        fn = _function(pin)
        if re.fullmatch(r"EPWM\d+[AB]", fn):
            lines.append(f"    // pin {pnum} {fn}: mux is applied by PWM init after clamp")
            continue
        mux = int(pin.get("mux", 0))
        option = _mux_option(pdef, pin)
        profile_name, profile = _profile_for(pin, option)
        lines.append(f"    // pin {pnum} {pdef['primary_signal']} -> {fn}; profile={profile_name}")
        if profile.get("note"):
            lines.append(f"    // {profile['note']}")
        lines.append(f"    {pdef['mux_field']} = {mux}U;")
        if mux == 0:
            direction = pin.get("direction", profile.get("direction", "output"))
            pullup = pin.get("pullup", profile.get("pullup", "disable"))
            if direction == "output":
                level = pin.get("initial_level", pin.get("level", "low"))
                field = pdef["set_field"] if level == "high" else pdef["clr_field"]
                lines.append(f"    {field} = 1U;   // preset {level} before DIR")
            lines.append(f"    {pdef['dir_field']} = {1 if direction == 'output' else 0}U;")
            lines.append(f"    {pdef['pud_field']} = {1 if pullup == 'disable' else 0}U;")
            if direction == "input":
                qual = pin.get("qualification", profile.get("qualification", "sync"))
                qvalue = {"sync": 0, "qual3": 1, "qual6": 2, "async": 3}[qual]
                qfield = pdef.get("qsel_field") or (
                    f"GpioCtrlRegs.{pdef.get('qsel_reg', 'GPAQSEL1')}.bit.GPIO"
                    f"{pdef.get('gpio_num')}")
                lines.append(f"    {qfield} = {qvalue}U;   // {qual}")
        else:
            pullup = profile.get("pullup", "disable")
            lines.append(f"    {pdef['pud_field']} = {1 if pullup == 'disable' else 0}U;")
            if profile.get("qualification"):
                qvalue = {"sync": 0, "qual3": 1, "qual6": 2, "async": 3}[
                    profile["qualification"]]
                qfield = pdef.get("qsel_field") or (
                    f"GpioCtrlRegs.{pdef.get('qsel_reg', 'GPAQSEL1')}.bit.GPIO"
                    f"{pdef.get('gpio_num')}")
                lines.append(f"    {qfield} = {qvalue}U;   // {profile['qualification']}")
        emitted += 1
    if not emitted:
        lines.append("    // no non-ePWM pins configured")
    lines += ["    EDIS;", "}"]
    c = "\n".join(lines) + "\n"
    h = HDR + "#ifndef PINMUX_INIT_H\n#define PINMUX_INIT_H\n\nvoid Generated_PinMux_Init(void);\n\n#endif\n"
    return {"pinmux_init.c": c, "pinmux_init.h": h}


def gen_clock(clock: dict | None) -> dict[str, str]:
    if not clock or clock.get("mode") in ("existing", "keep_existing"):
        return {}
    target = float(clock.get("target_mhz"))
    div = target * 2.0 / (INTOSC1_HZ / 1e6)
    div_i = int(round(div))
    if abs(div - div_i) > 1e-6 or not (1 <= div_i <= 15) or target > 60:
        raise ValueError(f"illegal system_clock target_mhz={target}")
    lines = [HDR, '#include "DSP2803x_Device.h"', '#include "DSP2803x_Examples.h"',
             '#include "system_clock_init.h"', "",
             "Uint16 Generated_SystemClock_Init(void)", "{",
             "    Uint32 lock_wait;",
             "    EALLOW;",
             "    SysCtrlRegs.WDCR = 0x0068U;",
             "    SysCtrlRegs.CLKCTL.bit.INTOSC1OFF = 0U;",
             "    SysCtrlRegs.CLKCTL.bit.OSCCLKSRCSEL = 0U;",
             "    SysCtrlRegs.PLLSTS.bit.DIVSEL = 0U;   // safe /4",
             "    SysCtrlRegs.PLLSTS.bit.MCLKOFF = 1U;",
             f"    SysCtrlRegs.PLLCR.bit.DIV = {div_i}U;",
             "    EDIS;",
             "    for (lock_wait = 0UL; lock_wait < 1000000UL; lock_wait++) {",
             "        if (SysCtrlRegs.PLLSTS.bit.PLLLOCKS != 0U) break;",
             "    }",
             "    if (SysCtrlRegs.PLLSTS.bit.PLLLOCKS == 0U) return 1U;",
             "    EALLOW;",
             "    SysCtrlRegs.PLLSTS.bit.MCLKOFF = 0U;",
             "    SysCtrlRegs.PLLSTS.bit.DIVSEL = 2U;   // /2",
             "    if (SysCtrlRegs.PLLSTS.bit.MCLKSTS != 0U) {",
             "        SysCtrlRegs.PLLSTS.bit.MCLKCLR = 1U;",
             "        EDIS;",
             "        return 1U;",
             "    }",
             "    EDIS;",
             "    return 0U;",
             "}"]
    c = "\n".join(lines) + "\n"
    h = (HDR + "#ifndef SYSTEM_CLOCK_INIT_H\n#define SYSTEM_CLOCK_INIT_H\n\n"
         '#include "DSP2803x_Device.h"\n'
         "Uint16 Generated_SystemClock_Init(void);\n\n#endif\n")
    return {"system_clock_init.c": c, "system_clock_init.h": h}


def _tbprd(sysclk_hz: int, freq: float, count_mode: str) -> int:
    denom = 2.0 * freq if count_mode == "up_down" else freq
    value = int(round(sysclk_hz / denom))
    if not (1 <= value <= 0xFFFF):
        raise ValueError(f"TBPRD={value} out of range for {freq}Hz {count_mode}")
    return value


def _aq(profile: str, count_mode: str, tbprd: int, duty: float) -> tuple[int, list[str]]:
    if not 0.0 < duty < 1.0:
        raise ValueError("PWM duty must be between 0 and 1")
    if count_mode == "up_down":
        if profile == "clear_cau_set_cad":
            cmpa = int(round(tbprd * duty))
            actions = ["AQCTLA.bit.CAU = 1U;", "AQCTLA.bit.CAD = 2U;"]
        else:
            cmpa = int(round(tbprd * (1.0 - duty)))
            actions = ["AQCTLA.bit.CAU = 2U;", "AQCTLA.bit.CAD = 1U;"]
    else:
        if profile == "clear_zro_set_cau":
            cmpa = int(round(tbprd * (1.0 - duty)))
            actions = ["AQCTLA.bit.ZRO = 1U;", "AQCTLA.bit.CAU = 2U;"]
        else:
            cmpa = int(round(tbprd * duty))
            actions = ["AQCTLA.bit.ZRO = 2U;", "AQCTLA.bit.CAU = 1U;"]
    if not 0 < cmpa < tbprd:
        raise ValueError(f"duty={duty} gives illegal CMPA={cmpa}")
    return cmpa, actions


def gen_pwm(config: dict, pinmux: dict, sysclk_hz: int) -> dict[str, str]:
    modules = config.get("pwm_modules", {}) or {}
    if not modules:
        return {}
    lines = [HDR, '#include "DSP2803x_Device.h"', '#include "pwm_init.h"', "",
             "void Generated_Pwm_Init(void)", "{", "    EALLOW;"]
    for name in sorted(modules):
        lines.append(f"    SysCtrlRegs.PCLKCR1.bit.{name}ENCLK = 1U;")
    lines += ["    SysCtrlRegs.PCLKCR0.bit.TBCLKSYNC = 0U;", ""]
    release = []
    for name in sorted(modules):
        m = modules[name]
        match = re.fullmatch(r"EPWM([1-7])", name.upper())
        if not match:
            raise ValueError(f"unsupported PWM module {name}")
        regs = f"EPwm{match.group(1)}Regs"
        freq = float(m["frequency_hz"])
        count_mode = m.get("count_mode", "up_down")
        tbprd = _tbprd(sysclk_hz, freq, count_mode)
        duty = float(m.get("duty", 0.5))
        aq_profile = m.get("aq_profile", "set_cau_clear_cad")
        cmpa, actions = _aq(aq_profile, count_mode, tbprd, duty)
        mode = m.get("mode", "single")
        pin_a = m.get("pin_a")
        pin_b = m.get("pin_b")
        if mode == "complementary" and (pin_a is None or pin_b is None):
            raise ValueError(f"{name} complementary requires pin_a and pin_b")
        trip = m.get("trip") or {}
        lines.append(f"    // {name}: {freq:g}Hz, {count_mode}, duty={duty:g}, AQ={aq_profile}")
        lines.append(f"    {regs}.TZCTL.bit.TZA = 2U;")
        lines.append(f"    {regs}.TZCTL.bit.TZB = 2U;")
        if trip.get("enabled"):
            source = str(trip.get("source", "TZ1")).upper().rstrip("N")
            sm = re.fullmatch(r"TZ([1-3])", source)
            if not sm:
                raise ValueError(f"{name} has unsupported trip source {source}")
            bit = "OSHT" if trip.get("mode", "one_shot") == "one_shot" else "CBC"
            lines.append(f"    {regs}.TZSEL.bit.{bit}{sm.group(1)} = 1U;")
        lines.append(f"    {regs}.TZFRC.bit.OST = 1U;   // clamp before pin mux")
        for channel, pnum in (("A", pin_a), ("B", pin_b)):
            if pnum is None:
                continue
            pdef = _pin_def(pinmux, pnum)
            fn = f"{name}{channel}"
            opt = next((x for x in pdef.get("mux_options", [])
                        if str(x.get("function", "")).upper() == fn), None)
            if not opt:
                raise ValueError(f"pin {pnum} does not provide {fn}")
            lines.append(f"    {pdef['pud_field']} = 1U;")
            lines.append(f"    {pdef['mux_field']} = {int(opt['mux'])}U;   // pin {pnum} -> {fn}")
        lines.append(f"    {regs}.TBCTL.bit.CTRMODE = {2 if count_mode == 'up_down' else 0}U;")
        lines.append(f"    {regs}.TBCTL.bit.HSPCLKDIV = 0U;")
        lines.append(f"    {regs}.TBCTL.bit.CLKDIV = 0U;")
        lines.append(f"    {regs}.TBPRD = {tbprd}U;")
        lines.append(f"    {regs}.CMPA.half.CMPA = {cmpa}U;")
        for action in actions:
            lines.append(f"    {regs}.{action}")
        dead = m.get("deadband") or {}
        if mode == "complementary":
            if not dead.get("enabled", True):
                raise ValueError(f"{name} complementary requires deadband")
            red = float(dead.get("red_ns", 0))
            fed = float(dead.get("fed_ns", 0))
            red_ticks = int(round(red * sysclk_hz / 1e9))
            fed_ticks = int(round(fed * sysclk_hz / 1e9))
            if not (1 <= red_ticks <= 1023 and 1 <= fed_ticks <= 1023):
                raise ValueError(f"{name} deadband ticks out of range")
            lines += [
                f"    {regs}.DBCTL.bit.IN_MODE = 0U;    // A is source",
                f"    {regs}.DBCTL.bit.OUT_MODE = 3U;",
                f"    {regs}.DBCTL.bit.POLSEL = 2U;     // active-high complementary",
                f"    {regs}.DBRED = {red_ticks}U;",
                f"    {regs}.DBFED = {fed_ticks}U;",
            ]
        lines += [f"    {regs}.TBCTR = 0U;", ""]
        release.append((name, regs))
    lines += ["    SysCtrlRegs.PCLKCR0.bit.TBCLKSYNC = 1U;", "    EDIS;", "}", ""]
    for name, regs in release:
        lines += [
            f"void {name}_ReleaseClamp(void)",
            "{", "    EALLOW;", f"    {regs}.TZCLR.bit.OST = 1U;", "    EDIS;", "}", ""
        ]
    c = "\n".join(lines)
    hlines = [HDR, "#ifndef PWM_INIT_H", "#define PWM_INIT_H", "",
              "void Generated_Pwm_Init(void);"]
    hlines += [f"void {name}_ReleaseClamp(void);" for name, _ in release]
    hlines += ["", "#endif", ""]
    return {"pwm_init.c": c, "pwm_init.h": "\n".join(hlines)}


def gen_adc(adc: dict | None) -> dict[str, str]:
    if not adc:
        return {}
    soc = int(adc["soc"])
    acqps = int(adc["acqps"])
    channel = adc["channel"]
    trigger = adc["trigger"]
    if not 0 <= soc <= 15 or not 0 <= acqps <= 63:
        raise ValueError("ADC SOC or ACQPS out of range")
    if channel not in ADC_CHSEL or trigger not in ADC_TRIGSEL:
        raise ValueError("ADC channel or trigger is not verified")
    lines = [HDR, '#include "DSP2803x_Device.h"', '#include "DSP2803x_Examples.h"',
             '#include "adc_init.h"', "", "void Generated_Adc_Init(void)", "{",
             "    EALLOW;",
             "    SysCtrlRegs.PCLKCR0.bit.ADCENCLK = 1U;",
             "    AdcRegs.ADCCTL1.bit.ADCBGPWD = 1U;",
             "    AdcRegs.ADCCTL1.bit.ADCREFPWD = 1U;",
             "    AdcRegs.ADCCTL1.bit.ADCPWDN = 1U;",
             "    AdcRegs.ADCCTL1.bit.ADCENABLE = 1U;",
             "    EDIS;", "    DELAY_US(1000L);", "    EALLOW;",
             f"    AdcRegs.ADCSOC{soc}CTL.bit.CHSEL = {ADC_CHSEL[channel]}U;",
             f"    AdcRegs.ADCSOC{soc}CTL.bit.TRIGSEL = {ADC_TRIGSEL[trigger]}U;",
             f"    AdcRegs.ADCSOC{soc}CTL.bit.ACQPS = {acqps}U;",
             "    EDIS;", "}"]
    c = "\n".join(lines) + "\n"
    h = HDR + "#ifndef ADC_INIT_H\n#define ADC_INIT_H\n\nvoid Generated_Adc_Init(void);\n\n#endif\n"
    return {"adc_init.c": c, "adc_init.h": h}


def gen_timers(timers: dict, sysclk_hz: int) -> dict[str, str]:
    if not timers:
        return {}
    lines = [HDR, '#include "DSP2803x_Device.h"', '#include "timer_interrupt_init.h"', ""]
    prototypes = []
    for name in sorted(timers):
        if name.upper() != "TIMER0":
            raise ValueError(f"unsupported timer {name}")
        t = timers[name]
        period_us = float(t["period_us"])
        prd = int(round(sysclk_hz * period_us / 1e6)) - 1
        if not 0 < prd <= 0xFFFFFFFF:
            raise ValueError(f"{name} period is out of range")
        isr = t.get("isr", "cpu_timer0_isr")
        prototypes += ["void Generated_Timer0_Init(void);", f"__interrupt void {isr}(void);"]
        lines += [
            "void Generated_Timer0_Init(void)", "{",
            "    EALLOW;",
            "    SysCtrlRegs.PCLKCR3.bit.CPUTIMER0ENCLK = 1U;",
            f"    PieVectTable.TINT0 = &{isr};",
            "    EDIS;", "    DINT;",
            f"    CpuTimer0Regs.PRD.all = {prd}UL;",
            "    CpuTimer0Regs.TCR.bit.TSS = 1U;",
            "    CpuTimer0Regs.TCR.bit.TIF = 1U;",
            "    PieCtrlRegs.PIEIER1.bit.INTx7 = 1U;",
            "    IER |= M_INT1;",
            "    CpuTimer0Regs.TCR.bit.TIE = 1U;",
            "    CpuTimer0Regs.TCR.bit.TSS = 0U;",
        ]
        if t.get("enable_global_interrupt"):
            lines += ["    EINT;", "    ERTM;"]
        lines += ["}", "", f"__interrupt void {isr}(void)", "{",
                  "    PieCtrlRegs.PIEACK.bit.ACK1 = 1U;", "}", ""]
    c = "\n".join(lines)
    h = HDR + "#ifndef TIMER_INTERRUPT_INIT_H\n#define TIMER_INTERRUPT_INIT_H\n\n" + \
        "\n".join(prototypes) + "\n\n#endif\n"
    return {"timer_interrupt_init.c": c, "timer_interrupt_init.h": h}


def gen_protection(protection: dict | None) -> dict[str, str]:
    if not protection:
        return {}
    c = (HDR + '#include "protection_init.h"\n\n'
         "void Generated_Protection_Init(void)\n{\n"
         "    // Project-selected protection policy is implemented in PWM Trip configuration.\n"
         "}\n")
    h = HDR + "#ifndef PROTECTION_INIT_H\n#define PROTECTION_INIT_H\n\nvoid Generated_Protection_Init(void);\n\n#endif\n"
    return {"protection_init.c": c, "protection_init.h": h}


def gen_init_all(config: dict, pinmux: dict, present: set[str]) -> dict[str, str]:
    pwm_pins = []
    for m in (config.get("pwm_modules", {}) or {}).values():
        for pnum in (m.get("pin_a"), m.get("pin_b")):
            if pnum is not None:
                pdef = _pin_def(pinmux, pnum)
                if pdef:
                    pwm_pins.append(pdef)
    includes = ['#include "generated_init_all.h"', '#include "pinmux_init.h"']
    calls = ["    Generated_PinMux_Init();"]
    if "system_clock_init.c" in present:
        includes.append('#include "system_clock_init.h"')
        calls.insert(0, "    if (Generated_SystemClock_Init() != 0U) return 1U;")
    if "pwm_init.c" in present:
        includes.append('#include "pwm_init.h"')
        calls.append("    Generated_Pwm_Init();")
    if "adc_init.c" in present:
        includes.append('#include "adc_init.h"')
        calls.append("    Generated_Adc_Init();")
    if "timer_interrupt_init.c" in present:
        includes.append('#include "timer_interrupt_init.h"')
        calls.append("    Generated_Timer0_Init();")
    if "protection_init.c" in present:
        includes.append('#include "protection_init.h"')
        calls.append("    Generated_Protection_Init();")
    lines = [HDR, *includes, "", "static void Generated_EmergencyShutdown(void)",
             "{", "    EALLOW;"]
    if not pwm_pins:
        lines.append("    // no ePWM pins configured")
    for p in pwm_pins:
        lines += [f"    {p['mux_field']} = 0U;",
                  f"    {p['clr_field']} = 1U;",
                  f"    {p['dir_field']} = 1U;",
                  f"    {p['pud_field']} = 1U;"]
    lines += ["    EDIS;", "}", "", "Uint16 Generated_InitAll(void)", "{",
              "    Generated_EmergencyShutdown();", *calls,
              "    return 0U;", "}"]
    c = "\n".join(lines) + "\n"
    h = (HDR + "#ifndef GENERATED_INIT_ALL_H\n#define GENERATED_INIT_ALL_H\n\n"
         '#include "DSP2803x_Device.h"\n'
         "Uint16 Generated_InitAll(void);\n\n#endif\n")
    return {"generated_init_all.c": c, "generated_init_all.h": h}


def _recommended(config: dict, files: dict, active_module: str | None) -> str:
    requested = (active_module or "").upper()
    if requested.startswith("EPWM") and "pwm_init.c" in files:
        return "pwm_init.c"
    if requested.startswith("ADC") and "adc_init.c" in files:
        return "adc_init.c"
    if requested.startswith("TIMER") and "timer_interrupt_init.c" in files:
        return "timer_interrupt_init.c"
    if requested and any(_function(pin) == requested for pin in _pins(config)):
        return "pinmux_init.c"
    if config.get("pwm_modules"):
        return "pwm_init.c"
    if config.get("adc"):
        return "adc_init.c"
    if config.get("timers"):
        return "timer_interrupt_init.c"
    return "pinmux_init.c"


def generate_project(device: str, project_config: dict, pinmux: dict,
                     family: dict, active_module: str | None = None) -> dict:
    config = dict(project_config or {})
    config.setdefault("device", device)
    config.setdefault("package", "PNT80")
    config.setdefault("system_clock", None)
    config.setdefault("pins", {})
    config.setdefault("pwm_modules", {})
    config.setdefault("adc", None)
    config.setdefault("timers", {})
    config.setdefault("protection", None)
    sysclk_hz = int((config.get("system_clock") or {}).get("sysclk_hz", MAX_SYSCLK_HZ))
    files: dict[str, str] = {}
    files.update(gen_pinmux(config, pinmux))
    files.update(gen_clock(config.get("system_clock")))
    files.update(gen_pwm(config, pinmux, sysclk_hz))
    files.update(gen_adc(config.get("adc")))
    files.update(gen_timers(config.get("timers") or {}, sysclk_hz))
    files.update(gen_protection(config.get("protection")))
    files.update(gen_init_all(config, pinmux, set(files)))
    files["generated_config.json"] = json.dumps(config, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    files["generation_report.md"] = (
        "# R3 Generation Report\n\n"
        f"- device: {config['device']}\n"
        f"- package: {config['package']}\n"
        f"- configured pins: {len(_pins(config))}\n"
        f"- configured PWM modules: {len(config['pwm_modules'])}\n"
        f"- ADC configured: {'yes' if config['adc'] else 'no'}\n"
        f"- timers configured: {len(config['timers'])}\n"
        "- preview/export generator: generate_project\n"
        "- PWM release: manual only\n"
    )
    recommended = _recommended(config, files, active_module)
    return {"files": files, "recommended_file": recommended,
            "active_module": active_module}


def generate(device, config, pinmux, family):
    """Backward-compatible R2 wrapper used by older callers."""
    return generate_project(device, config, pinmux, family)["files"]
