// ============================================================================
// AUTO-GENERATED by C2000 Config Studio for F28034 [R3]
// Deterministic output: preview and ZIP export use the same generator core.
// SAFETY: ePWM outputs remain clamped until the application explicitly calls
// the generated EPWMx_ReleaseClamp() function.
// ============================================================================
#ifndef GENERATED_INIT_ALL_H
#define GENERATED_INIT_ALL_H

#include "DSP2803x_Device.h"
Uint16 Generated_InitAll(void);

#endif
