// ============================================================================
// AUTO-GENERATED by C2000 Config Studio for F28034 [R3]
// Deterministic output: preview and ZIP export use the same generator core.
// SAFETY: ePWM outputs remain clamped until the application explicitly calls
// the generated EPWMx_ReleaseClamp() function.
// ============================================================================

#include "generated_init_all.h"
#include "pinmux_init.h"

static void Generated_EmergencyShutdown(void)
{
    EALLOW;
    // no ePWM pins configured
    EDIS;
}

Uint16 Generated_InitAll(void)
{
    Generated_EmergencyShutdown();
    Generated_PinMux_Init();
    return 0U;
}
