// ============================================================================
// AUTO-GENERATED by C2000 Config Studio for F28034 [R3]
// Deterministic output: preview and ZIP export use the same generator core.
// SAFETY: ePWM outputs remain clamped until the application explicitly calls
// the generated EPWMx_ReleaseClamp() function.
// ============================================================================

#include "DSP2803x_Device.h"
#include "pinmux_init.h"

void Generated_PinMux_Init(void)
{
    EALLOW;
    // pin 34 GPIO29 -> SCLA; profile=i2c_scla
    // I2C is open-drain; external pull-up resistors are required.
    GpioCtrlRegs.GPAMUX2.bit.GPIO29 = 2U;
    GpioCtrlRegs.GPAPUD.bit.GPIO29 = 0U;
    GpioCtrlRegs.GPAQSEL2.bit.GPIO29 = 3U;   // async
    EDIS;
}
