// ============================================================================
// AUTO-GENERATED by C2000 Config Studio for F28034 [R3]
// Deterministic output: preview and ZIP export use the same generator core.
// SAFETY: ePWM outputs remain clamped until the application explicitly calls
// the generated EPWMx_ReleaseClamp() function.
// ============================================================================
#ifndef PINMUX_INIT_H
#define PINMUX_INIT_H

void Generated_PinMux_Init(void);

#endif
