// ============================================================================
// AUTO-GENERATED by C2000 Config Studio for F28034 [R3]
// Deterministic output: preview and ZIP export use the same generator core.
// SAFETY: ePWM outputs remain clamped until the application explicitly calls
// the generated EPWMx_ReleaseClamp() function.
// ============================================================================

#include "DSP2803x_Device.h"
#include "pwm_init.h"

void Generated_Pwm_Init(void)
{
    EALLOW;
    SysCtrlRegs.PCLKCR1.bit.EPWM1ENCLK = 1U;
    SysCtrlRegs.PCLKCR0.bit.TBCLKSYNC = 0U;

    // EPWM1: 120000Hz, up_down, duty=0.45, AQ=set_cau_clear_cad
    EPwm1Regs.TZCTL.bit.TZA = 2U;
    EPwm1Regs.TZCTL.bit.TZB = 2U;
    EPwm1Regs.TZSEL.bit.OSHT1 = 1U;
    EPwm1Regs.TZFRC.bit.OST = 1U;   // clamp before pin mux
    GpioCtrlRegs.GPAPUD.bit.GPIO0 = 1U;
    GpioCtrlRegs.GPAMUX1.bit.GPIO0 = 1U;   // pin 69 -> EPWM1A
    GpioCtrlRegs.GPAPUD.bit.GPIO1 = 1U;
    GpioCtrlRegs.GPAMUX1.bit.GPIO1 = 1U;   // pin 68 -> EPWM1B
    EPwm1Regs.TBCTL.bit.CTRMODE = 2U;
    EPwm1Regs.TBCTL.bit.HSPCLKDIV = 0U;
    EPwm1Regs.TBCTL.bit.CLKDIV = 0U;
    EPwm1Regs.TBPRD = 250U;
    EPwm1Regs.CMPA.half.CMPA = 138U;
    EPwm1Regs.AQCTLA.bit.CAU = 2U;
    EPwm1Regs.AQCTLA.bit.CAD = 1U;
    EPwm1Regs.DBCTL.bit.IN_MODE = 0U;    // A is source
    EPwm1Regs.DBCTL.bit.OUT_MODE = 3U;
    EPwm1Regs.DBCTL.bit.POLSEL = 2U;     // active-high complementary
    EPwm1Regs.DBRED = 11U;
    EPwm1Regs.DBFED = 13U;
    EPwm1Regs.TBCTR = 0U;

    SysCtrlRegs.PCLKCR0.bit.TBCLKSYNC = 1U;
    EDIS;
}

void EPWM1_ReleaseClamp(void)
{
    EALLOW;
    EPwm1Regs.TZCLR.bit.OST = 1U;
    EDIS;
}
