/* R3.2 deterministic, browser-side C2000 code generator. */
(function (root, factory) {
  const json = root.DeterministicJSON ||
    (typeof require === 'function' ? require('./deterministic_json.js') : null);
  const checker = root.ConstraintChecker ||
    (typeof require === 'function' ? require('./constraint_checker.js') : null);
  const api = factory(json, checker);
  if (typeof module === 'object' && module.exports) module.exports = api;
  root.Codegen = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function (JSONCore, Checker) {
  'use strict';

  const MAX_SYSCLK_HZ = 60000000;
  const INTOSC1_HZ = 10000000;
  const HEADER = [
    '// AUTO-GENERATED BY C2000 CONFIG STUDIO R3.2 STATIC',
    '// 本文件由配置工具自动生成，文件编码为 UTF-8。',
    '// 给初学者：注释会解释每一步的目的，但不能代替 TI 数据手册和台架验证。',
    '// LOGIC TEST ONLY（仅用于逻辑测试）',
    '// NOT APPROVED FOR POWER-STAGE ENABLE（禁止据此直接开启功率级）',
    '// 使用前必须逐项核对寄存器、引脚、电平极性和硬件保护。',
    '',
  ].join('\n');

  const ADC_CHANNELS = Object.fromEntries(
    Array.from({ length: 8 }, (_, index) => [`ADCINA${index}`, index])
      .concat(Array.from({ length: 8 }, (_, index) => [`ADCINB${index}`, 8 + index])),
  );
  const ADC_TRIGGERS = {
    SOFTWARE: 0,
    CPUTIMER0: 1,
    CPUTIMER1: 2,
    CPUTIMER2: 3,
    EPWM1_SOCA: 5,
    EPWM1_SOCB: 6,
    EPWM2_SOCA: 7,
    EPWM2_SOCB: 8,
    EPWM3_SOCA: 9,
    EPWM3_SOCB: 10,
    EPWM4_SOCA: 11,
    EPWM4_SOCB: 12,
    EPWM5_SOCA: 13,
    EPWM5_SOCB: 14,
    EPWM6_SOCA: 15,
    EPWM6_SOCB: 16,
    EPWM7_SOCA: 17,
    EPWM7_SOCB: 18,
  };

  const PROFILES = {
    gpio_output: { direction: 'output', pullup: 'disable' },
    gpio_input: { direction: 'input', pullup: 'disable', qualification: 'sync' },
    epwm_output: { direction: 'output', pullup: 'disable' },
    trip_async_input: { direction: 'input', pullup: 'disable', qualification: 'async' },
    i2c_scla: { direction: 'input', pullup: 'enable', qualification: 'async' },
    i2c_sdaa: { direction: 'input', pullup: 'enable', qualification: 'async' },
    spi_input: { direction: 'input', pullup: 'disable', qualification: 'sync' },
    spi_output: { direction: 'output', pullup: 'disable' },
    sci_rx: { direction: 'input', pullup: 'enable', qualification: 'async' },
    sci_tx: { direction: 'output', pullup: 'disable' },
    eqep_input: { direction: 'input', pullup: 'enable', qualification: 'sync' },
  };

  function lineFile(lines) {
    return lines.join('\n') + '\n';
  }

  function configuredPins(config) {
    return Object.entries(config.pins || {}).map(([key, value]) => ({
      physical_pin: Number(value.physical_pin ?? key),
      ...value,
    })).sort((a, b) => a.physical_pin - b.physical_pin);
  }

  function pdef(pinmux, physicalPin) {
    return pinmux?.pins?.[String(Number(physicalPin))] || null;
  }

  function optionFor(pinmux, pin) {
    const def = pdef(pinmux, pin.physical_pin);
    return (def?.mux_options || []).find(option =>
      Number(option.mux) === Number(pin.mux) &&
      String(option.function).toUpperCase() === String(pin.function).toUpperCase(),
    ) || null;
  }

  function inferredProfile(pin, option) {
    if (pin.generator_profile && PROFILES[pin.generator_profile]) {
      return [pin.generator_profile, PROFILES[pin.generator_profile]];
    }
    if (option?.generator_profile && PROFILES[option.generator_profile]) {
      return [option.generator_profile, PROFILES[option.generator_profile]];
    }
    const fn = String(pin.function || '').toUpperCase();
    if (/^GPIO\d+$/.test(fn)) {
      const name = pin.direction === 'input' ? 'gpio_input' : 'gpio_output';
      return [name, PROFILES[name]];
    }
    if (/^TZ[1-3]N$/.test(fn)) return ['trip_async_input', PROFILES.trip_async_input];
    if (fn.includes('SDA')) return ['i2c_sdaa', PROFILES.i2c_sdaa];
    if (fn.includes('SCL')) return ['i2c_scla', PROFILES.i2c_scla];
    if (fn.includes('RX')) return ['sci_rx', PROFILES.sci_rx];
    if (fn.includes('TX')) return ['sci_tx', PROFILES.sci_tx];
    return ['gpio_input', PROFILES.gpio_input];
  }

  function generatePinmux(config, pinmux) {
    const lines = [
      HEADER.trimEnd(),
      '#include "DSP2803x_Device.h"',
      '#include "pinmux_init.h"',
      '',
      '// 本文件作用：把芯片物理脚切换到 ProjectConfig 选择的 GPIO 或外设功能。',
      '// 初学者提示：MUX 决定“这个脚接到芯片内部哪个模块”，DIR 决定输入或输出。',
      '// PUD 位的含义容易看反：PUD=1 是禁用内部上拉，PUD=0 才是启用内部上拉。',
      '',
      'void Generated_PinMux_Init(void)',
      '{',
      '    // EALLOW：允许写入受保护寄存器；配置完成后必须用 EDIS 重新保护。',
      '    EALLOW;',
    ];
    let emitted = 0;
    for (const pin of configuredPins(config)) {
      const def = pdef(pinmux, pin.physical_pin);
      if (!def?.configurable) continue;
      const fn = String(pin.function).toUpperCase();
      if (/^EPWM[1-7][AB]$/.test(fn)) {
        lines.push(
          `    // Pin${pin.physical_pin} ${fn} 由 pwm_init.c 配置，`,
          '    // 因为切换 PWM 引脚前必须先把输出钳位到安全低电平。',
        );
        continue;
      }
      const option = optionFor(pinmux, pin);
      if (!option) throw new Error(`Pin${pin.physical_pin} ${fn} has no exact MUX option`);
      const [profileName, profile] = inferredProfile(pin, option);
      lines.push(
        `    // Pin${pin.physical_pin}：${def.primary_signal} 切换为 ${option.function}；电气模板=${profileName}`,
        `    ${def.mux_field} = ${Number(option.mux)}U;   // 选择 MUX${Number(option.mux)} 功能`,
      );
      if (Number(option.mux) === 0) {
        const direction = pin.direction || profile.direction || 'output';
        const pullup = pin.pullup || profile.pullup || 'disable';
        if (direction === 'output') {
          const level = pin.initial_level || 'low';
          lines.push(
            '    // 先把输出锁存器写成目标电平，再设为输出，避免切换瞬间出现毛刺。',
            `    ${level === 'high' ? def.set_field : def.clr_field} = 1U;   // 预置为${level === 'high' ? '高' : '低'}电平`,
          );
        }
        lines.push(
          `    ${def.dir_field} = ${direction === 'output' ? 1 : 0}U;   // DIR：1=输出，0=输入`,
          `    ${def.pud_field} = ${pullup === 'disable' ? 1 : 0}U;   // PUD：1=禁用上拉，0=启用上拉`,
        );
        if (direction === 'input') {
          const qualification = pin.qualification || profile.qualification || 'sync';
          const value = { sync: 0, qual3: 1, qual6: 2, async: 3 }[qualification];
          const note = {
            sync: '同步输入',
            qual3: '连续 3 次采样确认',
            qual6: '连续 6 次采样确认',
            async: '异步输入（不等待采样资格）',
          }[qualification];
          lines.push(`    ${def.qsel_field} = ${value}U;   // 输入资格：${note}`);
        }
      } else {
        lines.push(
          `    ${def.pud_field} = ${profile.pullup === 'enable' ? 0 : 1}U;   // 配置该外设脚的内部上拉`,
        );
        if (profile.qualification) {
          const value = { sync: 0, qual3: 1, qual6: 2, async: 3 }[profile.qualification];
          const note = {
            sync: '同步输入',
            qual3: '连续 3 次采样确认',
            qual6: '连续 6 次采样确认',
            async: '异步输入（不经过同步采样资格，延迟更小）',
          }[profile.qualification];
          lines.push(`    ${def.qsel_field} = ${value}U;   // 输入资格：${note}`);
        }
      }
      emitted += 1;
    }
    if (!emitted) lines.push('    // 当前工程没有需要在这里配置的非 ePWM 引脚。');
    lines.push(
      '    EDIS;   // 重新禁止写受保护寄存器',
      '}',
    );
    return {
      'pinmux_init.c': lineFile(lines),
      'pinmux_init.h': lineFile([
        HEADER.trimEnd(),
        '#ifndef PINMUX_INIT_H',
        '#define PINMUX_INIT_H',
        '',
        '// 配置 ProjectConfig 中选定的非 ePWM 引脚复用和 GPIO 电气属性。',
        'void Generated_PinMux_Init(void);',
        '',
        '#endif',
      ]),
    };
  }

  function generateClock(clock) {
    if (!clock || ['existing', 'keep_existing'].includes(clock.mode)) return {};
    const targetMhz = Number(clock.target_mhz ?? Number(clock.sysclk_hz) / 1e6);
    const div = targetMhz * 2 / (INTOSC1_HZ / 1e6);
    const pllDiv = Math.round(div);
    if (!Number.isFinite(targetMhz) || Math.abs(div - pllDiv) > 1e-9 ||
        pllDiv < 1 || pllDiv > 15 || targetMhz > 60) {
      throw new Error(`illegal system_clock target_mhz=${targetMhz}`);
    }
    return {
      'system_clock_init.c': lineFile([
        HEADER.trimEnd(),
        '#include "DSP2803x_Device.h"',
        '#include "system_clock_init.h"',
        '',
        `// 本文件作用：使用芯片内部 10MHz 振荡器，把系统时钟配置为 ${targetMhz}MHz。`,
        '// 初学者提示：PLL 可以理解为“时钟倍频器”；切换时钟时必须先降速、等待锁定，再恢复高速。',
        '// 返回值：0=成功；1~4=不同阶段检测到时钟故障，调用者应停止后续初始化。',
        '',
        'Uint16 Generated_SystemClock_Init(void)',
        '{',
        '    Uint32 lock_wait;',
        '    // 下面这些时钟寄存器受保护，先用 EALLOW 临时开放写权限。',
        '    EALLOW;',
        '    SysCtrlRegs.WDCR = 0x0068U;   // 切换时钟期间暂时关闭看门狗，避免等待 PLL 时意外复位',
        '    SysCtrlRegs.CLKCTL.bit.INTOSC1OFF = 0U;   // 打开内部振荡器 1',
        '    SysCtrlRegs.CLKCTL.bit.OSCCLKSRCSEL = 0U; // 选择内部振荡器 1 作为 PLL 输入',
        '    // 第一次检查缺失时钟标志；若已有故障，不继续配置。',
        '    if (SysCtrlRegs.PLLSTS.bit.MCLKSTS != 0U) {',
        '        SysCtrlRegs.PLLSTS.bit.MCLKCLR = 1U;',
        '        EDIS;',
        '        return 1U;',
        '    }',
        '    SysCtrlRegs.PLLSTS.bit.DIVSEL = 0U;   // 先把 PLL 输出分频设为 /4，降低切换瞬间的风险',
        '    SysCtrlRegs.PLLSTS.bit.MCLKOFF = 1U;  // 修改 PLL 参数期间暂时关闭缺失时钟检测',
        '    SysCtrlRegs.PLLLOCKPRD = 0xFFFFU;     // 设置 PLL 锁定检测窗口',
        `    SysCtrlRegs.PLLCR.bit.DIV = ${pllDiv}U;   // PLL 倍频参数：最终得到 ${targetMhz}MHz SYSCLK`,
        '    EDIS;',
        '    // 等待 PLL 锁定。这里有超时上限，防止硬件异常时程序永久卡死。',
        '    for (lock_wait = 0UL; lock_wait < 1000000UL; lock_wait++) {',
        '        if (SysCtrlRegs.PLLSTS.bit.PLLLOCKS != 0U) break;',
        '    }',
        '    if (SysCtrlRegs.PLLSTS.bit.PLLLOCKS == 0U) return 2U;   // 超时：PLL 没有锁定',
        '    EALLOW;',
        '    // 锁定后再检查一次时钟故障，确认倍频过程没有丢失时钟。',
        '    if (SysCtrlRegs.PLLSTS.bit.MCLKSTS != 0U) {',
        '        SysCtrlRegs.PLLSTS.bit.MCLKCLR = 1U;',
        '        EDIS;',
        '        return 3U;',
        '    }',
        '    SysCtrlRegs.PLLSTS.bit.MCLKOFF = 0U;  // 重新开启缺失时钟检测',
        '    SysCtrlRegs.PLLSTS.bit.DIVSEL = 2U;   // 从安全低速切换到 PLL /2 的目标系统时钟',
        '    // 最后一次检查，确保切换到目标时钟后仍然正常。',
        '    if (SysCtrlRegs.PLLSTS.bit.MCLKSTS != 0U) {',
        '        SysCtrlRegs.PLLSTS.bit.MCLKCLR = 1U;',
        '        EDIS;',
        '        return 4U;',
        '    }',
        '    EDIS;   // 配置结束，恢复受保护寄存器的写保护',
        '    return 0U;   // 0 表示系统时钟初始化成功',
        '}',
      ]),
      'system_clock_init.h': lineFile([
        HEADER.trimEnd(),
        '#ifndef SYSTEM_CLOCK_INIT_H',
        '#define SYSTEM_CLOCK_INIT_H',
        '#include "DSP2803x_Device.h"',
        '// 配置系统时钟；返回 0 表示成功，非 0 表示时钟故障。',
        'Uint16 Generated_SystemClock_Init(void);',
        '#endif',
      ]),
    };
  }

  function tbprd(sysclk, frequency, countMode) {
    const value = Math.round(sysclk / ((countMode === 'up_down' ? 2 : 1) * frequency));
    if (!Number.isInteger(value) || value < 1 || value > 0xFFFF) {
      throw new Error(`TBPRD=${value} out of range`);
    }
    return value;
  }

  function aqSettings(profile, countMode, period, duty) {
    if (!(duty > 0 && duty < 1)) throw new Error('PWM duty must be in (0,1)');
    let compare;
    let actions;
    if (countMode === 'up_down') {
      if (profile === 'clear_cau_set_cad') {
        compare = Math.round(period * duty);
        actions = ['AQCTLA.bit.CAU = 1U;', 'AQCTLA.bit.CAD = 2U;'];
      } else {
        compare = Math.round(period * (1 - duty));
        actions = ['AQCTLA.bit.CAU = 2U;', 'AQCTLA.bit.CAD = 1U;'];
      }
    } else if (profile === 'clear_zro_set_cau') {
      compare = Math.round(period * (1 - duty));
      actions = ['AQCTLA.bit.ZRO = 1U;', 'AQCTLA.bit.CAU = 2U;'];
    } else {
      compare = Math.round(period * duty);
      actions = ['AQCTLA.bit.ZRO = 2U;', 'AQCTLA.bit.CAU = 1U;'];
    }
    if (compare <= 0 || compare >= period) throw new Error(`illegal CMPA=${compare}`);
    return { compare, actions };
  }

  function generatePwm(config, pinmux, sysclk) {
    const modules = config.pwm_modules || {};
    if (!Object.keys(modules).length) return {};
    const lines = [
      HEADER.trimEnd(),
      '#include "DSP2803x_Device.h"',
      '#include "pwm_init.h"',
      '',
      '// 本文件作用：配置 ePWM 的计数周期、占空比、动作规则、死区和硬件保护。',
      '// 初学者阅读顺序：TBCLK 驱动 TBCTR 计数，TBCTR 与 CMPA 比较，AQ 决定输出翻转，死区再生成互补波形。',
      '// 安全约定：Generated_Pwm_Init() 只完成配置并把输出钳在低电平；确认硬件安全后才可调用 ReleaseClamp()。',
      '',
      'void Generated_Pwm_Init(void)',
      '{',
      '    // ePWM 和时钟同步寄存器受保护，先开放写权限。',
      '    EALLOW;',
    ];
    const releases = [];
    Object.keys(modules).sort().forEach(name => {
      lines.push(
        `    SysCtrlRegs.PCLKCR1.bit.${name.toUpperCase()}ENCLK = 1U;   // 打开 ${name.toUpperCase()} 外设时钟`,
      );
    });
    lines.push(
      '    // 暂停所有 ePWM 的时间基准计数，避免寄存器还没配完就开始输出。',
      '    SysCtrlRegs.PCLKCR0.bit.TBCLKSYNC = 0U;',
      '',
    );

    Object.keys(modules).sort().forEach(rawName => {
      const name = rawName.toUpperCase();
      const match = /^EPWM([1-7])$/.exec(name);
      if (!match) throw new Error(`unsupported PWM module ${name}`);
      const module = modules[rawName];
      const regs = `EPwm${match[1]}Regs`;
      const countMode = module.count_mode || 'up_down';
      const period = tbprd(sysclk, Number(module.frequency_hz), countMode);
      const { compare, actions } = aqSettings(
        module.aq_profile || 'set_cau_clear_cad',
        countMode,
        period,
        Number(module.duty),
      );
      if (module.mode === 'complementary' &&
          (module.pin_a == null || module.pin_b == null)) {
        throw new Error(`${name} complementary requires A/B`);
      }
      const trip = module.trip || {};
      const countModeText = countMode === 'up_down' ? '上下计数（适合中心对齐 PWM）' : '向上计数';
      lines.push(
        `    // ===== ${name}：${module.frequency_hz}Hz，${countModeText}，占空比 ${Number(module.duty) * 100}% =====`,
        '    // Trip Zone 检测到保护事件时，强制 A、B 两路变为低电平。',
        `    ${regs}.TZCTL.bit.TZA = 2U;`,
        `    ${regs}.TZCTL.bit.TZB = 2U;`,
      );
      if (trip.enabled) {
        const source = String(trip.source || 'TZ1').toUpperCase().replace(/N$/, '');
        const tm = /^TZ([1-3])$/.exec(source);
        if (!tm) throw new Error(`${name} unsupported trip source ${source}`);
        const kind = trip.mode === 'cycle_by_cycle' ? 'CBC' : 'OSHT';
        const tripModeText = kind === 'CBC' ? '逐周期保护：每个周期可重新判断' : '一次触发锁存：必须由软件清除';
        lines.push(
          `    ${regs}.TZSEL.bit.${kind}${tm[1]} = 1U;   // 启用 ${source}，${tripModeText}`,
        );
      }
      lines.push(
        '    // 先保持软件强制低电平，并置位一次性 Trip；这样切换引脚 MUX 时不会突然输出脉冲。',
        `    ${regs}.AQCSFRC.bit.CSFA = 1U;   // 软件强制 A 路为低电平`,
        `    ${regs}.AQCSFRC.bit.CSFB = 1U;   // 软件强制 B 路为低电平`,
        `    ${regs}.TZFRC.bit.OST = 1U;      // 硬件保护继续钳位，形成第二道保险`,
      );
      for (const [channel, physicalPin] of [['A', module.pin_a], ['B', module.pin_b]]) {
        if (physicalPin == null) continue;
        const def = pdef(pinmux, physicalPin);
        const fn = `${name}${channel}`;
        const option = (def?.mux_options || []).find(item =>
          String(item.function).toUpperCase() === fn);
        if (!def || !option) throw new Error(`Pin${physicalPin} does not provide ${fn}`);
        lines.push(
          `    ${def.pud_field} = 1U;   // 禁用 Pin${physicalPin} 内部上拉，输出由 ePWM 外设驱动`,
          `    ${def.mux_field} = ${Number(option.mux)}U;   // 把物理脚 Pin${physicalPin} 连接到 ${fn}`,
        );
      }
      lines.push(
        `    ${regs}.TBCTL.bit.CTRMODE = ${countMode === 'up_down' ? 2 : 0}U;   // 选择${countModeText}`,
        `    ${regs}.TBCTL.bit.HSPCLKDIV = 0U;   // 高速时钟不分频`,
        `    ${regs}.TBCTL.bit.CLKDIV = 0U;      // 时间基准时钟不分频`,
        `    ${regs}.TBPRD = ${period}U;          // TBCTR 的计数边界，决定 PWM 频率`,
        `    ${regs}.CMPA.half.CMPA = ${compare}U; // 比较点，和 AQ 动作一起决定占空比`,
        '    // AQ（Action Qualifier，动作限定器）规定计数器遇到零点或比较点时，输出怎样变化。',
      );
      actions.forEach(action => lines.push(`    ${regs}.${action}`));
      if (module.mode === 'complementary') {
        const deadband = module.deadband || {};
        const red = Math.round(Number(deadband.red_ns) * sysclk / 1e9);
        const fed = Math.round(Number(deadband.fed_ns) * sysclk / 1e9);
        if (red < 1 || red > 1023 || fed < 1 || fed > 1023) {
          throw new Error(`${name} deadband ticks out of range`);
        }
        lines.push(
          '    // 互补 PWM 的上下管不能同时导通，因此在上升沿和下降沿之间插入死区。',
          `    ${regs}.DBCTL.bit.IN_MODE = 0U;   // A 路作为死区模块输入`,
          `    ${regs}.DBCTL.bit.OUT_MODE = 3U;  // 同时启用上升沿和下降沿延时`,
          `    ${regs}.DBCTL.bit.POLSEL = 2U;    // 生成互补的 A/B 输出`,
          `    ${regs}.DBRED = ${red}U;          // 上升沿死区：${deadband.red_ns}ns`,
          `    ${regs}.DBFED = ${fed}U;          // 下降沿死区：${deadband.fed_ns}ns`,
        );
      }
      lines.push(
        `    ${regs}.TBPHS.half.TBPHS = 0U;   // 相位从 0 开始`,
        `    ${regs}.TBCTR = 0U;              // 计数器从 0 开始`,
        '',
      );
      const tripPin = trip.enabled ? pdef(pinmux, trip.pin) : null;
      releases.push({ name, regs, tripPin });
    });
    lines.push(
      '    // 所有模块都配置完成后再统一启动时间基准；输出仍被软件和 Trip 钳在低电平。',
      '    SysCtrlRegs.PCLKCR0.bit.TBCLKSYNC = 1U;',
      '    EDIS;   // 恢复受保护寄存器的写保护',
      '}',
      '',
    );

    for (const release of releases) {
      lines.push(
        `Uint16 ${release.name}_ReleaseClamp(void)`,
        '{',
      );
      if (release.tripPin) {
        lines.push(
          '    // 第 1 步：先读硬件 Trip 输入。低电平表示故障仍存在，此时绝不能放开 PWM。',
          `    if (${release.tripPin.dat_field} == 0U) return 1U;`,
        );
      } else {
        lines.push(
          '    // 第 1 步：本模块没有配置硬件 Trip 输入，调用者必须自行确认母线、驱动和负载都安全。',
        );
      }
      lines.push(
        '    // 第 2 步：继续保持软件低电平，防止清除 Trip 的过程中出现窄脉冲。',
        '    EALLOW;',
        `    ${release.regs}.AQCSFRC.bit.CSFA = 1U;`,
        `    ${release.regs}.AQCSFRC.bit.CSFB = 1U;`,
        '    // 第 3 步：暂停所有 ePWM 计数器，准备从确定的零点重新启动。',
        '    SysCtrlRegs.PCLKCR0.bit.TBCLKSYNC = 0U;',
        '    // 第 4 步：把计数器和相位都归零，使重新启动的第一个周期可预测。',
        `    ${release.regs}.TBCTR = 0U;`,
        `    ${release.regs}.TBPHS.half.TBPHS = 0U;`,
        '    // 第 5 步：清除 Trip 中断、逐周期和一次性锁存标志。',
        `    ${release.regs}.TZCLR.bit.INT = 1U;`,
        `    ${release.regs}.TZCLR.bit.CBC = 1U;`,
        `    ${release.regs}.TZCLR.bit.OST = 1U;`,
        '    // 第 6 步：先恢复时间基准，再解除软件钳位，让输出从完整周期边界开始。',
        '    SysCtrlRegs.PCLKCR0.bit.TBCLKSYNC = 1U;',
        `    ${release.regs}.AQCSFRC.bit.CSFA = 0U;`,
        `    ${release.regs}.AQCSFRC.bit.CSFB = 0U;`,
        '    EDIS;',
        '    return 0U;   // 0 表示已成功放开钳位；此后 PWM 脉冲会真正输出到引脚',
        '}',
        '',
      );
    }
    const headerLines = [
      HEADER.trimEnd(),
      '#ifndef PWM_INIT_H',
      '#define PWM_INIT_H',
      '#include "DSP2803x_Device.h"',
      '// 只配置 PWM 并保持低电平钳位，不会直接放出驱动脉冲。',
      'void Generated_Pwm_Init(void);',
      '// 在硬件安全条件全部满足后放开对应模块；返回 0=成功，有硬件 Trip 时返回 1=故障输入仍有效。',
      ...releases.map(release => `Uint16 ${release.name}_ReleaseClamp(void);`),
      '#endif',
    ];
    return {
      'pwm_init.c': lineFile(lines),
      'pwm_init.h': lineFile(headerLines),
    };
  }

  function generateAdc(adc) {
    if (!adc) return {};
    const soc = Number(adc.soc);
    const acqps = Number(adc.acqps);
    const channel = String(adc.channel || '').toUpperCase();
    const trigger = String(adc.trigger || '').toUpperCase();
    if (!Number.isInteger(soc) || soc < 0 || soc > 15 ||
        !Number.isInteger(acqps) || acqps < 0 || acqps > 63 ||
        ADC_CHANNELS[channel] == null || ADC_TRIGGERS[trigger] == null) {
      throw new Error('ADC setting is not verified');
    }
    return {
      'adc_init.c': lineFile([
        HEADER.trimEnd(),
        '#include "DSP2803x_Device.h"',
        '#include "DSP2803x_Examples.h"',
        '#include "adc_init.h"',
        '',
        '// 本文件作用：给 ADC 上电，并配置一个 SOC（Start Of Conversion，启动一次转换的任务槽）。',
        '// 初学者提示：每个 SOC 都要回答三个问题——采哪个通道、由谁触发、采样窗口有多长。',
        '',
        'void Generated_Adc_Init(void)',
        '{',
        '    // 第一步：打开 ADC 外设时钟，并给内部基准、模拟电路和 ADC 核心上电。',
        '    EALLOW;',
        '    SysCtrlRegs.PCLKCR0.bit.ADCENCLK = 1U;   // 打开 ADC 外设时钟',
        '    AdcRegs.ADCCTL1.bit.ADCBGPWD = 1U;       // 给带隙基准上电',
        '    AdcRegs.ADCCTL1.bit.ADCREFPWD = 1U;      // 给参考电压电路上电',
        '    AdcRegs.ADCCTL1.bit.ADCPWDN = 1U;        // 给 ADC 模拟核心上电',
        '    AdcRegs.ADCCTL1.bit.ADCENABLE = 1U;      // 允许 ADC 工作',
        '    EDIS;',
        '    DELAY_US(1000L);   // 等待 1ms，让内部基准和模拟电路稳定',
        '    // 第二步：配置具体的 SOC。注意，ACQPS 寄存器值 N 表示实际采样 N+1 个 ADC 时钟周期。',
        '    EALLOW;',
        `    AdcRegs.ADCSOC${soc}CTL.bit.CHSEL = ${ADC_CHANNELS[channel]}U;   // SOC${soc} 采样 ${channel}`,
        `    AdcRegs.ADCSOC${soc}CTL.bit.TRIGSEL = ${ADC_TRIGGERS[trigger]}U; // 由 ${trigger} 启动转换`,
        `    AdcRegs.ADCSOC${soc}CTL.bit.ACQPS = ${acqps}U;    // 采样窗口为 ${acqps + 1} 个 ADC 时钟周期`,
        '    EDIS;   // 恢复受保护寄存器的写保护',
        '}',
      ]),
      'adc_init.h': lineFile([
        HEADER.trimEnd(),
        '#ifndef ADC_INIT_H',
        '#define ADC_INIT_H',
        '// 给 ADC 上电并配置工程选择的 SOC。',
        'void Generated_Adc_Init(void);',
        '#endif',
      ]),
    };
  }

  function generateTimers(timers, sysclk) {
    if (!Object.keys(timers || {}).length) return {};
    const lines = [
      HEADER.trimEnd(),
      '#include "DSP2803x_Device.h"',
      '#include "timer_interrupt_init.h"',
      '',
      '// 本文件作用：配置 CPU Timer0 周期中断，并提供一个最小的中断服务函数框架。',
      '// 初学者提示：Timer0 计数到期后，先经过 CPU 中断组，再经过 PIE，最后才会进入下面的 ISR。',
      '',
    ];
    const prototypes = [];
    for (const rawName of Object.keys(timers).sort()) {
      const name = rawName.toUpperCase();
      if (name !== 'TIMER0') throw new Error(`unsupported timer ${name}`);
      const timer = timers[rawName];
      const period = Math.round(sysclk * Number(timer.period_us) / 1e6) - 1;
      if (!Number.isInteger(period) || period <= 0 || period > 0xFFFFFFFF) {
        throw new Error(`${name} period is out of range`);
      }
      const isr = timer.isr || 'cpu_timer0_isr';
      prototypes.push(
        '// 配置 Timer0 的周期和中断通路。',
        'void Generated_Timer0_Init(void);',
        '// Timer0 中断服务函数；在这里添加任务时应保持代码短小。',
        `__interrupt void ${isr}(void);`,
      );
      lines.push(
        'void Generated_Timer0_Init(void)',
        '{',
        '    // 先停止计数器并关闭其中断，防止配置尚未完成就进入 ISR。',
        '    CpuTimer0Regs.TCR.bit.TSS = 1U;   // TSS=1：停止 Timer0',
        '    CpuTimer0Regs.TCR.bit.TIE = 0U;   // TIE=0：暂时禁止 Timer0 中断',
        '    CpuTimer0Regs.TCR.bit.TIF = 1U;   // 写 1 清除可能残留的到期标志',
        `    CpuTimer0Regs.PRD.all = ${period}UL;   // 周期寄存器，对应 ${timer.period_us}us`,
        '    CpuTimer0Regs.TCR.bit.TRB = 1U;   // 把新周期装入计数器',
        '    // 打开外设时钟，并把 PIE 向量表中的 Timer0 入口指向本文件的 ISR。',
        '    EALLOW;',
        '    SysCtrlRegs.PCLKCR3.bit.CPUTIMER0ENCLK = 1U;   // 打开 Timer0 时钟',
        `    PieVectTable.TINT0 = &${isr};   // 登记中断服务函数地址`,
        '    EDIS;',
        '    // 中断需要同时打通 PIE 第 1 组第 7 路，以及 CPU 的 INT1 总开关。',
        '    PieCtrlRegs.PIEIER1.bit.INTx7 = 1U;   // 允许 PIE1.7（Timer0）',
        '    IER |= M_INT1;                        // 允许 CPU 中断组 1',
        '    CpuTimer0Regs.TCR.bit.TIE = 1U;       // 允许 Timer0 产生中断请求',
        `    CpuTimer0Regs.TCR.bit.TSS = ${timer.start_immediately === false ? 1 : 0}U;   // ${timer.start_immediately === false ? '先保持停止，等待业务代码手动启动' : '立即开始计数'}`,
        '}',
        '',
        `__interrupt void ${isr}(void)`,
        '{',
        '    // TODO：把真正的周期任务写在这里，但不要执行耗时很长的代码。',
        '    // 必须应答 PIE 第 1 组，否则同组后续中断会一直被挡住。',
        '    PieCtrlRegs.PIEACK.bit.ACK1 = 1U;',
        '}',
        '',
      );
    }
    return {
      'timer_interrupt_init.c': lineFile(lines),
      'timer_interrupt_init.h': lineFile([
        HEADER.trimEnd(),
        '#ifndef TIMER_INTERRUPT_INIT_H',
        '#define TIMER_INTERRUPT_INIT_H',
        ...prototypes,
        '#endif',
      ]),
    };
  }

  function generateProtection(protection) {
    if (!protection) return {};
    return {
      'protection_init.c': lineFile([
        HEADER.trimEnd(),
        '#include "protection_init.h"',
        '',
        '// 本文件保留统一的保护初始化入口，方便主程序按固定顺序调用。',
        '// 当前工程选择的 Trip Zone 硬件保护已在 pwm_init.c 中配置，这里不重复写寄存器。',
        'void Generated_Protection_Init(void)',
        '{',
        '    // 目前没有额外动作；以后增加比较器或外部故障链时，可在证据确认后扩展。',
        '}',
      ]),
      'protection_init.h': lineFile([
        HEADER.trimEnd(),
        '#ifndef PROTECTION_INIT_H',
        '#define PROTECTION_INIT_H',
        '// 执行工程选择的额外保护初始化。',
        'void Generated_Protection_Init(void);',
        '#endif',
      ]),
    };
  }

  function generateInitAll(config, pinmux, present) {
    const pwmPins = [];
    Object.values(config.pwm_modules || {}).forEach(module => {
      [module.pin_a, module.pin_b].forEach(pin => {
        const def = pin == null ? null : pdef(pinmux, pin);
        if (def) pwmPins.push(def);
      });
    });
    const includes = ['#include "generated_init_all.h"', '#include "pinmux_init.h"'];
    const calls = [
      '    // 配置普通 GPIO 和通信外设引脚；ePWM 引脚由 PWM 初始化函数安全地接管。',
      '    Generated_PinMux_Init();',
    ];
    if (present.has('system_clock_init.c')) {
      includes.push('#include "system_clock_init.h"');
      calls.unshift(
        '    // 先建立可靠系统时钟；若返回非 0，立即停止，避免后续模块使用错误时钟。',
        '    if (Generated_SystemClock_Init() != 0U) return 1U;',
      );
    }
    if (present.has('pwm_init.c')) {
      includes.push('#include "pwm_init.h"');
      calls.push(
        '    // 配置 PWM，但输出仍保持低电平钳位，不会在这里直接启动功率级。',
        '    Generated_Pwm_Init();',
      );
    }
    if (present.has('adc_init.c')) {
      includes.push('#include "adc_init.h"');
      calls.push(
        '    // 给 ADC 上电并建立采样任务。',
        '    Generated_Adc_Init();',
      );
    }
    if (present.has('timer_interrupt_init.c')) {
      includes.push('#include "timer_interrupt_init.h"');
      calls.push(
        '    // 配置周期定时器和中断入口。',
        '    Generated_Timer0_Init();',
      );
    }
    if (present.has('protection_init.c')) {
      includes.push('#include "protection_init.h"');
      calls.push(
        '    // 最后执行工程选择的额外保护初始化。',
        '    Generated_Protection_Init();',
      );
    }
    const lines = [
      HEADER.trimEnd(),
      ...includes,
      '',
      '// 本文件是所有生成代码的统一入口。主程序只需调用 Generated_InitAll()。',
      '// 安全原则：第一件事先把所有 PWM 相关引脚退回 GPIO 并拉低，然后才初始化各外设。',
      '',
      'static void Generated_EmergencyShutdown(void)',
      '{',
      '    // 把 ePWM 引脚切回普通 GPIO 低电平，防止上电复位状态或旧配置产生误脉冲。',
      '    EALLOW;',
    ];
    if (!pwmPins.length) lines.push('    // 当前工程没有配置 ePWM 引脚，因此这里无需执行紧急拉低。');
    pwmPins.forEach(def => lines.push(
      '    // MUX=0 切回 GPIO；先写低电平锁存器，再设为输出，避免方向切换毛刺。',
      `    ${def.mux_field} = 0U;   // 临时选择 GPIO 功能`,
      `    ${def.clr_field} = 1U;   // 输出锁存器预置为低电平`,
      `    ${def.dir_field} = 1U;   // GPIO 设为输出`,
      `    ${def.pud_field} = 1U;   // 禁用内部上拉`,
    ));
    lines.push(
      '    EDIS;   // 恢复受保护寄存器的写保护',
      '}',
      '',
      'Uint16 Generated_InitAll(void)',
      '{',
      '    // 第 1 步永远是安全关断；后面任何初始化失败，PWM 引脚都已经处于低电平。',
      '    Generated_EmergencyShutdown();',
      ...calls,
      '    return 0U;   // 所有初始化完成；注意 PWM 仍未解除钳位',
      '}',
    );
    return {
      'generated_init_all.c': lineFile(lines),
      'generated_init_all.h': lineFile([
        HEADER.trimEnd(),
        '#ifndef GENERATED_INIT_ALL_H',
        '#define GENERATED_INIT_ALL_H',
        '#include "DSP2803x_Device.h"',
        '// 执行安全关断和全部生成初始化；返回 0=成功，非 0=初始化失败。',
        'Uint16 Generated_InitAll(void);',
        '#endif',
      ]),
    };
  }

  function recommendedFile(config, files, activeModule) {
    const requested = String(activeModule || '').toUpperCase();
    if (requested.startsWith('EPWM') && files['pwm_init.c']) return 'pwm_init.c';
    if (requested.startsWith('ADC') && files['adc_init.c']) return 'adc_init.c';
    if (requested.startsWith('TIMER') && files['timer_interrupt_init.c']) {
      return 'timer_interrupt_init.c';
    }
    if (requested && configuredPins(config)
      .some(pin => String(pin.function).toUpperCase() === requested)) return 'pinmux_init.c';
    if (files['pwm_init.c']) return 'pwm_init.c';
    if (files['adc_init.c']) return 'adc_init.c';
    if (files['timer_interrupt_init.c']) return 'timer_interrupt_init.c';
    return 'pinmux_init.c';
  }

  function generationReport(config, warnings) {
    return [
      '# R3.2 静态代码生成报告',
      '',
      '- 状态：LOGIC TEST ONLY（仅用于逻辑测试）',
      '- 功率级许可：NOT APPROVED FOR POWER-STAGE ENABLE（禁止直接开启功率级）',
      `- 芯片：${config.device}`,
      `- 封装：${config.package}`,
      `- 已配置引脚数：${configuredPins(config).length}`,
      `- 已配置 PWM 模块数：${Object.keys(config.pwm_modules || {}).length}`,
      `- ADC：${config.adc ? '已配置' : '未配置'}`,
      `- 定时器数量：${Object.keys(config.timers || {}).length}`,
      '- 生成器运行环境：浏览器端 JavaScript',
      '- PWM 放行方式：必须由调用者在完成硬件安全检查后显式调用 ReleaseClamp()',
      '',
      '## 警告',
      '',
      ...(warnings.length ? warnings.map(item => `- ${item}`) : ['- 无']),
      '',
    ].join('\n');
  }

  function generateProject(project, context = {}) {
    const config = JSONCore.clone(project);
    const pinmux = context.pinmux;
    const family = context.family || {};
    const validation = Checker.validateProject(config, pinmux, family);
    if (!validation.ok) {
      const error = new Error(validation.blocking.map(item => item.message).join('；'));
      error.validation = validation;
      throw error;
    }
    const sysclk = Number(config.system_clock?.sysclk_hz ||
      Number(config.system_clock?.target_mhz) * 1e6) || MAX_SYSCLK_HZ;
    const files = {};
    Object.assign(files, generatePinmux(config, pinmux));
    Object.assign(files, generateClock(config.system_clock));
    Object.assign(files, generatePwm(config, pinmux, sysclk));
    Object.assign(files, generateAdc(config.adc));
    Object.assign(files, generateTimers(config.timers || {}, sysclk));
    Object.assign(files, generateProtection(config.protection));
    Object.assign(files, generateInitAll(config, pinmux, new Set(Object.keys(files))));
    files['generated_config.json'] = JSONCore.stringify(config, 2) + '\n';
    const warnings = validation.findings
      .filter(item => item.severity === 'WARNING')
      .map(item => item.message);
    warnings.unshift('生成源码在任何功率级使用前都必须经过工程师审查。');
    files['generation_report.md'] = generationReport(config, warnings);
    const ordered = Object.keys(files).sort().reduce((out, name) => {
      out[name] = files[name];
      return out;
    }, {});
    return {
      files: ordered,
      recommended_file: recommendedFile(config, ordered, context.activeModule),
      active_module: context.activeModule || null,
      findings: validation.findings,
      ok: true,
    };
  }

  return {
    HEADER,
    generateProject,
    generatePinmux,
    generateClock,
    generatePwm,
    generateAdc,
    generateTimers,
  };
});
